# Generated by Django 2.1.3 on 2018-12-19 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_auto_20181214_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='lat',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tarea',
            name='lng',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
