# Generated by Django 2.1.3 on 2018-12-19 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_auto_20181219_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
