# Generated by Django 2.1.3 on 2018-12-20 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_auto_20181219_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='user',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
