# Generated by Django 2.1.3 on 2018-12-20 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_tarea_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarea',
            old_name='user',
            new_name='username',
        ),
    ]
