# Generated by Django 2.1.3 on 2018-12-20 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_auto_20181220_1204'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarea',
            old_name='username',
            new_name='nombre_usuario',
        ),
    ]
